export const diacriticsMap = {
  // --- Lowercase Letters ---

  // Alpha (α)
  ἀ: ["α", "smooth"],
  ἁ: ["α", "rough"],
  ἄ: ["α", "smooth", "acute"],
  ἅ: ["α", "rough", "acute"],
  ἂ: ["α", "smooth", "grave"],
  ἃ: ["α", "rough", "grave"],
  ἆ: ["α", "smooth", "circumflex"],
  ἇ: ["α", "rough", "circumflex"],
  ὰ: ["α", "grave"],
  ά: ["α", "acute"],
  ᾶ: ["α", "circumflex"],
  ᾳ: ["α", "subscript"],
  ᾀ: ["α", "smooth", "subscript"],
  ᾁ: ["α", "rough", "subscript"],
  ᾂ: ["α", "smooth", "grave", "subscript"],
  ᾃ: ["α", "rough", "grave", "subscript"],
  ᾄ: ["α", "smooth", "acute", "subscript"],
  ᾅ: ["α", "rough", "acute", "subscript"],
  ᾆ: ["α", "smooth", "circumflex", "subscript"],
  ᾇ: ["α", "rough", "circumflex", "subscript"],

  // Epsilon (ε)
  ἐ: ["ε", "smooth"],
  ἑ: ["ε", "rough"],
  ἔ: ["ε", "smooth", "acute"],
  ἕ: ["ε", "rough", "acute"],
  ἒ: ["ε", "smooth", "grave"],
  ἓ: ["ε", "rough", "grave"],
  ὲ: ["ε", "grave"],
  έ: ["ε", "acute"],

  // Eta (η)
  ἠ: ["η", "smooth"],
  ἡ: ["η", "rough"],
  ἤ: ["η", "smooth", "acute"],
  ἥ: ["η", "rough", "acute"],
  ἢ: ["η", "smooth", "grave"],
  ἣ: ["η", "rough", "grave"],
  ἦ: ["η", "smooth", "circumflex"],
  ἧ: ["η", "rough", "circumflex"],
  ὴ: ["η", "grave"],
  ή: ["η", "acute"],
  ῆ: ["η", "circumflex"],
  ῃ: ["η", "subscript"],
  ᾐ: ["η", "smooth", "subscript"],
  ᾑ: ["η", "rough", "subscript"],
  ᾒ: ["η", "smooth", "grave", "subscript"],
  ᾓ: ["η", "rough", "grave", "subscript"],
  ᾔ: ["η", "smooth", "acute", "subscript"],
  ᾕ: ["η", "rough", "acute", "subscript"],
  ᾖ: ["η", "smooth", "circumflex", "subscript"],
  ᾗ: ["η", "rough", "circumflex", "subscript"],

  // Iota (ι)
  ἰ: ["ι", "smooth"],
  ἱ: ["ι", "rough"],
  ἴ: ["ι", "smooth", "acute"],
  ἵ: ["ι", "rough", "acute"],
  ἲ: ["ι", "smooth", "grave"],
  ἳ: ["ι", "rough", "grave"],
  ἶ: ["ι", "smooth", "circumflex"],
  ἷ: ["ι", "rough", "circumflex"],
  ὶ: ["ι", "grave"],
  ί: ["ι", "acute"],
  ῖ: ["ι", "circumflex"],
  ϊ: ["ι", "diaeresis"],
  ΐ: ["ι", "diaeresis", "acute"],
  ῒ: ["ι", "diaeresis", "grave"],
  ῗ: ["ι", "diaeresis", "circumflex"],

  // Omicron (ο)
  ὀ: ["ο", "smooth"],
  ὁ: ["ο", "rough"],
  ὄ: ["ο", "smooth", "acute"],
  ὅ: ["ο", "rough", "acute"],
  ὂ: ["ο", "smooth", "grave"],
  ὃ: ["ο", "rough", "grave"],
  ὸ: ["ο", "grave"],
  ό: ["ο", "acute"],

  // Upsilon (υ)
  ὐ: ["υ", "smooth"],
  ὑ: ["υ", "rough"],
  ὔ: ["υ", "smooth", "acute"],
  ὕ: ["υ", "rough", "acute"],
  ὒ: ["υ", "smooth", "grave"],
  ὓ: ["υ", "rough", "grave"],
  ὖ: ["υ", "smooth", "circumflex"],
  ὗ: ["υ", "rough", "circumflex"],
  ὺ: ["υ", "grave"],
  ύ: ["υ", "acute"],
  ῦ: ["υ", "circumflex"],
  ϋ: ["υ", "diaeresis"],
  ΰ: ["υ", "diaeresis", "acute"],
  ῢ: ["υ", "diaeresis", "grave"],
  ῧ: ["υ", "diaeresis", "circumflex"],

  // Omega (ω)
  ὠ: ["ω", "smooth"],
  ὡ: ["ω", "rough"],
  ὤ: ["ω", "smooth", "acute"],
  ὥ: ["ω", "rough", "acute"],
  ὢ: ["ω", "smooth", "grave"],
  ὣ: ["ω", "rough", "grave"],
  ὦ: ["ω", "smooth", "circumflex"],
  ὧ: ["ω", "rough", "circumflex"],
  ὼ: ["ω", "grave"],
  ώ: ["ω", "acute"],
  ῶ: ["ω", "circumflex"],
  ῳ: ["ω", "subscript"],
  ᾠ: ["ω", "smooth", "subscript"],
  ᾡ: ["ω", "rough", "subscript"],
  ῷ: ["ω", "circumflex", "subscript"],
  ᾢ: ["ω", "smooth", "grave", "subscript"],
  ᾣ: ["ω", "rough", "grave", "subscript"],
  ᾤ: ["ω", "smooth", "acute", "subscript"],
  ᾥ: ["ω", "rough", "acute", "subscript"],
  ᾦ: ["ω", "smooth", "circumflex", "subscript"],
  ᾧ: ["ω", "rough", "circumflex", "subscript"],

  // Rho (ρ)
  ῤ: ["ρ", "smooth"],
  ῥ: ["ρ", "rough"],

  // --- Capital Letters ---

  // Alpha (Α)
  Ἀ: ["Α", "smooth"],
  Ἁ: ["Α", "rough"],
  Ἄ: ["Α", "smooth", "acute"],
  Ἅ: ["Α", "rough", "acute"],
  Ἂ: ["Α", "smooth", "grave"],
  Ἃ: ["Α", "rough", "grave"],
  Ἆ: ["Α", "smooth", "circumflex"],
  Ἇ: ["Α", "rough", "circumflex"],
  ᾈ: ["Α", "smooth", "subscript"],
  ᾉ: ["Α", "rough", "subscript"],
  ᾊ: ["Α", "smooth", "grave", "subscript"],
  ᾋ: ["Α", "rough", "grave", "subscript"],
  ᾌ: ["Α", "smooth", "acute", "subscript"],
  ᾍ: ["Α", "rough", "acute", "subscript"],
  ᾎ: ["Α", "smooth", "circumflex", "subscript"],
  ᾏ: ["Α", "rough", "circumflex", "subscript"],

  // Epsilon (Ε)
  Ἐ: ["Ε", "smooth"],
  Ἑ: ["Ε", "rough"],
  Ἔ: ["Ε", "smooth", "acute"],
  Ἕ: ["Ε", "rough", "acute"],
  Ἒ: ["Ε", "smooth", "grave"],
  Ἓ: ["Ε", "rough", "grave"],

  // Eta (Η)
  Ἠ: ["Η", "smooth"],
  Ἡ: ["Η", "rough"],
  Ἤ: ["Η", "smooth", "acute"],
  Ἥ: ["Η", "rough", "acute"],
  Ἢ: ["Η", "smooth", "grave"],
  Ἣ: ["Η", "rough", "grave"],
  Ἦ: ["Η", "smooth", "circumflex"],
  Ἧ: ["Η", "rough", "circumflex"],
  ᾘ: ["Η", "smooth", "subscript"],
  ᾙ: ["Η", "rough", "subscript"],
  ᾚ: ["Η", "smooth", "grave", "subscript"],
  ᾛ: ["Η", "rough", "grave", "subscript"],
  ᾜ: ["Η", "smooth", "acute", "subscript"],
  ᾝ: ["Η", "rough", "acute", "subscript"],
  ᾞ: ["Η", "smooth", "circumflex", "subscript"],
  ᾟ: ["Η", "rough", "circumflex", "subscript"],

  // Iota (Ι)
  Ἰ: ["Ι", "smooth"],
  Ἱ: ["Ι", "rough"],
  Ἴ: ["Ι", "smooth", "acute"],
  Ἵ: ["Ι", "rough", "acute"],
  Ἲ: ["Ι", "smooth", "grave"],
  Ἳ: ["Ι", "rough", "grave"],
  Ἶ: ["Ι", "smooth", "circumflex"],
  Ἷ: ["Ι", "rough", "circumflex"],
  Ῐ: ["Ι", "grave"], // capital iota with grave, etc. are rare
  Ῑ: ["Ι", "acute"],
  Ὶ: ["Ι", "grave"],
  Ί: ["Ι", "acute"],

  // Omicron (Ο)
  Ὀ: ["Ο", "smooth"],
  Ὁ: ["Ο", "rough"],
  Ὄ: ["Ο", "smooth", "acute"],
  Ὅ: ["Ο", "rough", "acute"],
  Ὂ: ["Ο", "smooth", "grave"],
  Ὃ: ["Ο", "rough", "grave"],

  // Upsilon (Υ)
  Ὑ: ["Υ", "rough"],
  Ὕ: ["Υ", "rough", "acute"],
  Ὓ: ["Υ", "rough", "grave"],
  Ὗ: ["Υ", "rough", "circumflex"],
  Ῠ: ["Υ", "grave"],
  Ῡ: ["Υ", "acute"],
  Ὺ: ["Υ", "diaeresis", "grave"],
  Ύ: ["Υ", "diaeresis", "acute"],

  // Omega (Ω)
  Ὠ: ["Ω", "smooth"],
  Ὡ: ["Ω", "rough"],
  Ὤ: ["Ω", "smooth", "acute"],
  Ὥ: ["Ω", "rough", "acute"],
  Ὢ: ["Ω", "smooth", "grave"],
  Ὣ: ["Ω", "rough", "grave"],
  Ὦ: ["Ω", "smooth", "circumflex"],
  Ὧ: ["Ω", "rough", "circumflex"],
  ᾨ: ["Ω", "smooth", "subscript"],
  ᾩ: ["Ω", "rough", "subscript"],
  ᾪ: ["Ω", "smooth", "grave", "subscript"],
  ᾫ: ["Ω", "rough", "grave", "subscript"],
  ᾬ: ["Ω", "smooth", "acute", "subscript"],
  ᾭ: ["Ω", "rough", "acute", "subscript"],
  ᾮ: ["Ω", "smooth", "circumflex", "subscript"],
  ᾯ: ["Ω", "rough", "circumflex", "subscript"],

  // Rho (Ρ)
  Ῥ: ["Ρ", "rough"],
};
